//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7.SyndicationClient.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IWsDvrFeed")]
    public interface IWsDvrFeed {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsDvrFeed/CreateFeed", ReplyAction="http://tempuri.org/IWsDvrFeed/CreateFeedResponse")]
        System.ServiceModel.Syndication.SyndicationFeedFormatter CreateFeed();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsDvrFeed/CreateFeed", ReplyAction="http://tempuri.org/IWsDvrFeed/CreateFeedResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Syndication.SyndicationFeedFormatter> CreateFeedAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsDvrFeedChannel : Lab7.SyndicationClient.ServiceReference.IWsDvrFeed, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsDvrFeedClient : System.ServiceModel.ClientBase<Lab7.SyndicationClient.ServiceReference.IWsDvrFeed>, Lab7.SyndicationClient.ServiceReference.IWsDvrFeed {
        
        public WsDvrFeedClient() {
        }
        
        public WsDvrFeedClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsDvrFeedClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsDvrFeedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsDvrFeedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ServiceModel.Syndication.SyndicationFeedFormatter CreateFeed() {
            return base.Channel.CreateFeed();
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Syndication.SyndicationFeedFormatter> CreateFeedAsync() {
            return base.Channel.CreateFeedAsync();
        }
    }
}
